use std::{
    fmt::{self, Write},
    mem,
    ops::Range,
};

use itertools::Itertools as _;
use kurbo::{BezPath, ParamCurve as _, ParamCurveNearest as _, PathEl, Shape as _};
use monoxide_curves::{CubicBezier, CubicSegment, point::Point2D};
use monoxide_script::{ast::Glyph, eval::eval_outline};

use crate::{make_font_params, prelude::*};

const PRECISION: usize = 4;

pub struct SvgPen<W> {
    buf: W,
    scale: Scale,
}

impl<W: Write> SvgPen<W> {
    pub fn new(buf: W, scale: Scale) -> Self {
        Self { buf, scale }
    }

    fn draw_point(&mut self, p: &Point2D) -> fmt::Result {
        let sc = self.scale;
        writeln!(
            self.buf,
            " {:.PRECISION$} {:.PRECISION$}",
            sc.x * p.x,
            sc.y * p.y
        )
    }

    fn draw_start(&mut self, p: &Point2D) -> fmt::Result {
        write!(self.buf, "M")?;
        self.draw_point(p)
    }

    fn draw_close(&mut self) -> fmt::Result {
        writeln!(self.buf, "Z")
    }

    fn draw_el(&mut self, el: &CubicSegment) -> fmt::Result {
        match el {
            CubicSegment::Line(p) => {
                write!(self.buf, "L")?;
                self.draw_point(p)
            }
            CubicSegment::Curve(p, q, r) => {
                write!(self.buf, "C")?;
                for pt in [p, q, r] {
                    self.draw_point(pt)?;
                }
                Ok(())
            }
        }
    }

    pub fn draw_contour(&mut self, contour: &CubicBezier) -> fmt::Result {
        self.draw_start(&contour.start)?;

        for el in &contour.segments {
            self.draw_el(el)?
        }
        if contour.closed {
            self.draw_close()?;
        }
        Ok(())
    }

    pub fn draw_glyph(&mut self, glyph: &Glyph) -> anyhow::Result<()> {
        for outline in &glyph.outlines {
            let mut contours = vec![];
            eval_outline(outline, &mut contours, &mut ()).unwrap();
            for contour in &contours {
                self.draw_contour(contour)?;
            }
        }
        Ok(())
    }
}

impl<W: Write + Default> SvgPen<W> {
    pub fn finish(&mut self) -> W {
        mem::take(&mut self.buf)
    }
}

#[derive(Debug, Clone)]
pub struct ViewBox {
    xs: Range<f64>,
    ys: Range<f64>,
    scale: Scale,
}

impl ViewBox {
    pub fn new(scale: Scale) -> Self {
        let FontParamSettingsView { dsc, asc, .. } = make_font_params().view();

        Self {
            xs: (0.)..1.,
            ys: dsc..asc,
            scale,
        }
    }
}

impl fmt::Display for ViewBox {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = self.scale;
        let padding = 0.25;
        let x0 = s.x * (self.xs.start - padding);
        let x1 = s.x * (self.xs.end + padding);
        let y0 = s.y * (self.ys.start - padding);
        let y1 = s.y * (self.ys.end + padding);
        write!(
            f,
            "{x:.PRECISION$} {y:.PRECISION$} {dx:.PRECISION$} {dy:.PRECISION$}",
            x = x0.min(x1),
            y = y0.min(y1),
            dx = (x1 - x0).abs(),
            dy = (y1 - y0).abs(),
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Scale {
    pub x: f64,
    pub y: f64,
}

impl Default for Scale {
    fn default() -> Self {
        Self { x: 1., y: -1. }
    }
}

/// Checks whether two SVGs draw the same shapes. The path data is compared
/// geometrically, so tiny floating-point drifts, different starting points of
/// closed contours and zero-length segments do not matter. The rest of the SVG
/// must match exactly.
pub fn equiv(a: &str, b: &str) -> bool {
    /// Maximum allowed distance between two equivalent paths, which is slightly
    /// more than the rounding error of the coordinates printed by
    /// [`svg::SvgPen`].
    const SVG_TOLERANCE: f64 = 1.5e-4;

    /// Number of points sampled on each segment when comparing two paths.
    const SAMPLES_PER_SEG: usize = 16;

    /// Accuracy of the nearest-point and perimeter computations.
    const ACCURACY: f64 = 1e-9;

    fn subpaths_count(path: &BezPath) -> usize {
        path.elements()
            .iter()
            .filter(|el| matches!(el, PathEl::MoveTo(_)))
            .count()
    }

    /// Splits an SVG into the text before the path data, the path data itself,
    /// and the text after it.
    ///
    /// The parsing rules are very simple and do not handle all valid SVGs, but
    /// they are good enough for the SVGs generated by [`SvgPen`] in this case.
    fn sections(svg: &str) -> Option<(&str, &str, &str)> {
        const OPEN: &str = " d=\"";
        let start = svg.find(OPEN)? + OPEN.len();
        let len = svg[start..].find('"')?;
        Some((&svg[..start], &svg[start..start + len], &svg[start + len..]))
    }

    /// Checks whether every sampled point on `a` lies within [`SVG_TOLERANCE`]
    /// of `b`.
    fn is_within_tolerance(a: &BezPath, b: &BezPath) -> bool {
        let segs_b = b.segments().collect_vec();
        let tolerance_sq = SVG_TOLERANCE.powi(2);
        a.segments()
            .cartesian_product(0..=SAMPLES_PER_SEG)
            .all(|(seg_a, i)| {
                let pt_a = seg_a.eval(i as f64 / SAMPLES_PER_SEG as f64);
                segs_b
                    .iter()
                    .map(|seg_b| seg_b.nearest(pt_a, ACCURACY).distance_sq)
                    .fold(f64::INFINITY, f64::min)
                    <= tolerance_sq
            })
    }

    if let Some(((pre_a, d_a, post_a), (pre_b, d_b, post_b))) = sections(a).zip(sections(b))
        && (pre_a, post_a) == (pre_b, post_b)
        && let (Ok(a), Ok(b)) = (BezPath::from_svg(d_a), BezPath::from_svg(d_b))
    {
        return subpaths_count(&a) == subpaths_count(&b)
            // The area is signed, so this also catches reversed contours.
            && (a.area() - b.area()).abs() <= SVG_TOLERANCE * a.perimeter(ACCURACY)
            && is_within_tolerance(&a, &b)
            && is_within_tolerance(&b, &a);
    };

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    fn svg(d: &str) -> String {
        format!(r#"<svg><path d="{d}" fill="black" /></svg>"#)
    }

    const TRIANGLE: &str = r#"M 0.2127 -0.7000
L 1.0000 -0.0000
L 1.0000 -1.0000
Z"#;

    #[test]
    fn equiv_id() {
        assert!(equiv(&svg(TRIANGLE), &svg(TRIANGLE)));
    }

    #[test]
    fn equiv_small_drift() {
        assert!(equiv(
            &svg(TRIANGLE),
            &svg(r#"M 0.2128 -0.7001
L 1.0000 0.0000
L 1.0000 -1.0000
Z"#)
        ));

        assert!(!equiv(
            &svg(TRIANGLE),
            &svg(r#"M 0.2129 -0.7000
L 1.0000 -0.0000
L 1.0000 -1.0000
Z"#)
        ));
    }

    #[test]
    fn equiv_closed_contour_start() {
        assert!(equiv(
            &svg(TRIANGLE),
            &svg(r#"M 1.0000 -0.0000
L 1.0000 -1.0000
L 0.2127 -0.7000
Z"#)
        ));
    }

    #[test]
    fn equiv_zero_length_segments() {
        assert!(equiv(
            &svg(TRIANGLE),
            &svg(r#"M 0.2127 -0.7000
L 0.2127 -0.7000
L 1.0000 -0.0000
C 1.0000 -0.0000 1.0000 -0.0000 1.0000 -0.0000
L 1.0000 -1.0000
Z"#)
        ));
    }

    #[test]
    fn equiv_contour_reversed() {
        assert!(!equiv(
            &svg(TRIANGLE),
            &svg(r#"M 0.2127 -0.7000
L 1.0000 -1.0000
L 1.0000 -0.0000
Z"#)
        ));
    }

    #[test]
    fn equiv_different() {
        assert!(!equiv(
            &svg(TRIANGLE),
            &svg(r#"M 0.2127 -0.7000
L 1.0000 -0.0000
Z"#)
        ));
    }

    #[test]
    fn equiv_open_vs_close() {
        assert!(!equiv(
            &svg(TRIANGLE),
            &svg(r#"M 0.2127 -0.7000
L 1.0000 -0.0000
L 1.0000 -1.0000"#)
        ));
    }

    #[test]
    fn equiv_empty() {
        assert!(!equiv(&svg(TRIANGLE), "<svg></svg>"));
    }
}
