"""
Simple script to generate language IDs from the Microsoft list.

Each line of the file is a hexadecimal number representing a language ID,
followed by a space and the language name.

Some language names have a comment separated from the BCP 47 tag by a comma.
The comment is not included in the generated file. Some other language codes
are reserved, and they are also not included in the generated file.


# The list

The Microsoft Language ID list is a direct plaintext copy of the list found in
"[MS-LCID]: Windows Language Code Identifier (LCID) Reference", which can be
found in the link below.

The list is copyrighted by Microsoft. The use of the list here is explicitly
granted by the license of the document.

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f

"""

from pathlib import Path
import re

lang_id_file = Path(__file__).parent / "lang_id_ms.txt"
output_file = Path(__file__).parent / "lang_id_ms.rs"

is_reserved_re = re.compile(r"^(.*), reserved$", re.IGNORECASE)
skip_re = re.compile(
    r"unassigned|local without assigned LCID|neither|^reserved|without",
    re.IGNORECASE,
)
lang_id_sep = re.compile(r"[_-]")


def normalize_lang_id(lang_id: str) -> str:
    parts = lang_id_sep.split(lang_id)
    return "_".join(parts).lower()


def main():
    with lang_id_file.open("r") as f:
        data = f.readlines()

    lang_names_and_ids = []
    for line in data:
        line = line.strip()
        if not line:
            continue

        [tag_value, lang_name] = line.split(" ", 1)

        if skip_re.search(lang_name):
            continue
        m = is_reserved_re.match(lang_name)
        if m:
            lang_name = m.group(1)
        lang_name = lang_name.split(",")[0]

        lang_name = normalize_lang_id(lang_name)
        if m:
            lang_name = f"{lang_name}_reserved"

        tag_value = tag_value.lower()

        lang_names_and_ids.append((tag_value, lang_name))

    # Remove duplicated tags
    lang_names_and_ids = list(dict(lang_names_and_ids).items())

    with output_file.open("w") as f:
        f.write("""
//! Language IDs from the Microsoft list.
//!
//! This file is generated using the `gen_lang_id_ms.py` script found next to this file.
//! Do not edit this file by hand.

#[allow(non_camel_case_types, unused)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
/// Language IDs as defined by Microsoft.
pub enum MSLangID {
""")
        for tag_value, lang_name in lang_names_and_ids:
            f.write(f"    r#{lang_name} = {tag_value},\n")
        f.write("}\n")

    # Run rustfmt
    import subprocess

    subprocess.run(["rustfmt", str(output_file)])


if __name__ == "__main__":
    main()
