[package]
name = "monoxide-curves"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
itertools.workspace = true
kurbo.workspace = true
monoxide-spiro.workspace = true
serde.workspace = true
thiserror.workspace = true
